### ISSUE TITLE
Using terragrunt

### ISSUE THREAD

**Issue by pyguy** [aliscott/infracost#12] opened 2020-07-27 16:24 UTC
Hey @aliscott, I can use infracost with terraform binary without any troubles, but using [terragrunt](https://github.com/gruntwork-io/terragrunt) as TERRAFORM_BIRANY fails with the following error:

```
$ infracost --tfplan  /tmp/plan.save --tfdir .

INFO Running command: /Users/hamidreza.josheghani.nl/bin/terragrunt show -json /tmp/plan.save 
ERROR [terragrunt] 2020/07/27 18:20:09 Reading Terragrunt config file at /Users/hamidreza.josheghani.nl/.terragrunt-cache/JUfGA5wi4WTKJQMziGewY--KhGo/s2C_bji1SyqpvI6oza4fKa5ohpw/mgmt/jenkins/terragrunt.hcl 
ERROR [terragrunt] 2020/07/27 18:20:09 /Users/hamidreza.josheghani.nl/.terragrunt-cache/JUfGA5wi4WTKJQMziGewY--KhGo/s2C_bji1SyqpvI6oza4fKa5ohpw/mgmt/jenkins/terragrunt.hcl:24,10-33: Error in function call; Call to function "find_in_parent_folders" failed: ParentFileNotFound: Could not find a terragrunt.hcl in any of the parent folders of /Users/hamidreza.josheghani.nl/.terragrunt-cache/JUfGA5wi4WTKJQMziGewY--KhGo/s2C_bji1SyqpvI6oza4fKa5ohpw/mgmt/jenkins/terragrunt.hcl. Cause: Traversed all the way to the root.., and 1 other diagnostic(s) 
ERROR [terragrunt] 2020/07/27 18:20:09 Unable to determine underlying exit code, so Terragrunt will exit with error code 1 
exit status 1
➜  jenkins git:(65d6dba) ✗ cd ~/Documents/DevOps/bits/in/infrastructure-live/shared-services/us-west-2/mgmt/jenkins                                      
➜  jenkins git:(master) avshrd  infracost --tfplan  /tmp/plan.save --tfdir .                                    
INFO Running command: /Users/hamidreza.josheghani.nl/bin/terragrunt show -json /tmp/plan.save 
ERROR [terragrunt] 2020/07/27 18:20:18 Reading Terragrunt config file at /Users/hamidreza.josheghani.nl/Documents/DevOps/bits/in/infrastructure-live/shared-services/us-west-2/mgmt/jenkins/terragrunt.hcl 
ERROR [terragrunt] [/Users/hamidreza.josheghani.nl/Documents/DevOps/bits/in/infrastructure-live/shared-services/us-west-2/mgmt/jenkins] 2020/07/27 18:20:18 Running command: terraform --version 
ERROR [terragrunt] 2020/07/27 18:20:18 Terraform files in /Users/hamidreza.josheghani.nl/.terragrunt-cache/JUfGA5wi4WTKJQMziGewY--KhGo/s2C_bji1SyqpvI6oza4fKa5ohpw/mgmt/jenkins are up to date. Will not download again. 
ERROR [terragrunt] 2020/07/27 18:20:18 Copying files from /Users/hamidreza.josheghani.nl/Documents/DevOps/bits/in/infrastructure-live/shared-services/us-west-2/mgmt/jenkins into /Users/hamidreza.josheghani.nl/.terragrunt-cache/JUfGA5wi4WTKJQMziGewY--KhGo/s2C_bji1SyqpvI6oza4fKa5ohpw/mgmt/jenkins 
ERROR [terragrunt] 2020/07/27 18:20:18 Setting working directory to /Users/hamidreza.josheghani.nl/.terragrunt-cache/JUfGA5wi4WTKJQMziGewY--KhGo/s2C_bji1SyqpvI6oza4fKa5ohpw/mgmt/jenkins 
ERROR [terragrunt] 2020/07/27 18:20:20 Running command: terraform show -json /tmp/plan.save 
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
infracost/pkg/parsers/terraform.parseModule(0x5, 0xc0003e0000, 0x64593, 0x0, 0x0, 0x0, 0x0, 0x5, 0xc00041e5d2, 0xab, ...)
        /Users/ali/code/infracost/pkg/parsers/terraform/terraform.go:156 +0x10af
infracost/pkg/parsers/terraform.parseModule(0x5, 0xc0003e0000, 0x64593, 0x0, 0x0, 0x0, 0x0, 0x5, 0xc00041e5d2, 0xab, ...)
        /Users/ali/code/infracost/pkg/parsers/terraform/terraform.go:176 +0xd01
infracost/pkg/parsers/terraform.parseModule(0x5, 0xc0003e0000, 0x64593, 0x0, 0x0, 0x0, 0x0, 0x5, 0xc00041e5d2, 0xab, ...)
        /Users/ali/code/infracost/pkg/parsers/terraform/terraform.go:176 +0xd01
infracost/pkg/parsers/terraform.ParsePlanJSON(0xc000360000, 0x64593, 0x7fe00, 0xe, 0xc000360000, 0x64593, 0x7fe00, 0x0)
        /Users/ali/code/infracost/pkg/parsers/terraform/terraform.go:145 +0x382
main.main.func2(0xc000154a80, 0xc000128e00, 0xe)
        /Users/ali/code/infracost/cmd/infracost/main.go:123 +0x256
github.com/urfave/cli/v2.(*App).RunContext(0xc000132180, 0x151d4e0, 0xc000134008, 0xc000138000, 0x5, 0x5, 0x0, 0x0)
        /Users/ali/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:315 +0x70b
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/ali/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
        /Users/ali/code/infracost/cmd/infracost/main.go:153 +0x4fb
```

Due to the terragrunt being a wrapper around terraform, I expected the same result running infracost with terragrunt binary.  I maybe have a wrong assumption, but wanted to ask you about this.

Thanks for this awesome tool :-)

**Comment by aliscott** [comment] 2020-07-30 19:00
@pyguy thanks! I fixed the cause of this stack trace in #13. Can you try [v0.3.2](https://github.com/aliscott/infracost/releases/tag/v0.3.2) and see if it works?

**Comment by pyguy** [comment] 2020-07-31 08:06
Thanks @aliscott ! 
Getting `invalid memory address or nil pointer dereference` this time:
```
INFO Running command: /Users/hamidreza.josheghani/bin/terraform show -json /tmp/plan.save
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1369406]

goroutine 1 [running]:
infracost/internal/terraform/aws.(*Ec2AutoscalingGroup).PriceComponents(0xc0002f57b0, 0x0, 0x0, 0x1826c80)
	/Users/ali/code/infracost/internal/terraform/aws/ec2_autoscaling_group.go:105 +0x26
infracost/pkg/base.(*GraphQLQueryRunner).batchQueries(0xc00045b690, 0x151f4a0, 0xc0002f57b0, 0x142a020, 0x275, 0x0, 0x10, 0x10, 0xc00045b6a0)
	/Users/ali/code/infracost/pkg/base/query.go:91 +0x96
infracost/pkg/base.(*GraphQLQueryRunner).RunQueries(0xc00045b690, 0x151f4a0, 0xc0002f57b0, 0xc0002a1aa0, 0x0, 0x0)
	/Users/ali/code/infracost/pkg/base/query.go:124 +0x5a
infracost/pkg/base.GenerateCostBreakdowns(0x1515e60, 0xc00045b690, 0xc00023f0c0, 0x4, 0x4, 0xc0002ca1b0, 0x30, 0x0, 0x0, 0xc000210e80)
	/Users/ali/code/infracost/pkg/base/costs.go:93 +0x634
main.main.func2(0xc00023ea80, 0xc000210e00, 0xe)
	/Users/ali/code/infracost/cmd/infracost/main.go:129 +0x389
github.com/urfave/cli/v2.(*App).RunContext(0xc00021c180, 0x151d580, 0xc00021e008, 0xc000222000, 0x5, 0x5, 0x0, 0x0)
	/Users/ali/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:315 +0x70b
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/ali/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
	/Users/ali/code/infracost/cmd/infracost/main.go:153 +0x4fb
```

**Comment by aliscott** [comment] 2020-07-31 08:25
@pyguy thanks. This looks like the same issue as #10. I'm adding support for `mixed_instances_policy` for autoscaling groups which should fix this.

**Comment by aliscott** [comment] 2020-08-07 16:02
@pyguy can you try [v0.4.0](https://github.com/aliscott/infracost/issues/10) and see if that resolves your issue? If you have any opinions about [the questions here](https://github.com/aliscott/infracost/issues/10#issuecomment-670588121) please feel free to answer on that issue.

I'll close this in favor of #10 just now since the original terragrunt issue is resolved.

**Closed by aliscott** 2020-08-07 16:02 UTC

**Comment by pyguy** [comment] 2020-08-09 15:02
@aliscott Yeah I tried v0.4.0 and it's working. Thanks a lot.
